server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forest?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



# JWT??
secretKey: ThisIsAStrongSecretKeyWithAtLeast32BytesLength!!
durationInMinute: 60

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.demos
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      column-underline: true  # 确保没有强制映射下划线字段


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true